# -*- coding: utf-8 -*-
"""project_weather_and_png.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IDGbTuWLjT0-AsvN9Zw1vy-sKq7Wovjc
"""

import requests
#import os
from datetime import datetime
 
api_key = '54d2a87403ec9d831ecf25ecf2e35dee'
location = input("Enter the city name: ")
 
complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()
 
#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")
 
print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")
 
print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')

import requests
 
r = requests.get('https://xkcd.com/353/')
 
print(r)

import requests
 
r = requests.get( 'https://xkcd.com/353/')
 
print(dir(r))

import requests
 
r = requests.get('https://xkcd.com/353/')
 
print(r.text)

import requests
 
r = requests.get('https://imgs.xkcd.com/comics/python.png')
 
print (r.text)
 
# returns html of the page we are requesting

import requests
 
r = requests.get('https://imgs.xkcd.com/comics/python.png')
 
print(r.content)
 
# returns html of the page we are requesting

import requests
 
r = requests.get('https://imgs.xkcd.com/comics/python.png')
 
with open('comic.png','wb') as f:
    f.write(r.content)